name: Build golang-cross-builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - name: Build and Publish the Docker image to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: mengdaming/golang-cross/golang-cross-builder
        username: mengdaming
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile.builder
        registry: docker.pkg.github.com
        tags: "latest,v1.16.7-fyne.1"
    
    - name: Build and Publish the Docker image to ghcr.io
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: mengdaming/golang-cross-builder
        username: mengdaming
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile.builder
        registry: ghcr.io
        tags: "latest,v1.16.7-fyne.1"